name: baseline+smart_init
model: facebook/bart-large
#model: facebook/bart-base

# <--------------
# Linearizations
# Comment DFS and uncomment the relevant block if you want to use a different linearization scheme

# DFS
penman_linearization: True
use_pointer_tokens: True
raw_graph: False



remove_wiki: False
dereify: False
collapse_name_ops: False

#
# Hparams
batch_size: 500
beam_size: 1
dropout: 0.25
attention_dropout: 0.0
smart_init: True
accum_steps: 10
warmup_steps: 1
training_steps: 250000
weight_decay: 0.004
grad_norm: 2.5
scheduler: constant
learning_rate: 0.00005
max_epochs: 30
save_checkpoints: True
log_wandb: False
warm_start: True
use_recategorization: False
best_loss: False
remove_longer_than: 1024



#dep_vocab_file: configs/dep_gold_vocab.txt
dep_vocab_file: configs/dep_gold_vocab_Allen.txt
srl_vocab_file: configs/srl_gold_vocab.txt

# ------------------Data---------------------------------
#---------------sample
train: data/AMR/sample/train.txt
dev: data/AMR/sample/dev.txt
test: data/AMR/sample/test.txt

train_dep_file: data/AMR/sample/train_dep.json
dev_dep_file: data/AMR/sample/dev_dep.json
train_srl_file: data/AMR/sample/train_srl.json
dev_srl_file: data/AMR/sample/dev_srl.json



#----------------AMR2.0
#test: data/AMR/amr_2.0/test.txt
#train: data/AMR/amr_2.0/train.txt
#dev: data/AMR/amr_2.0/dev.txt
#train_dep_file: data/AMR/amr_2.0/amr2.0_train_dep_Allen.json
#dev_dep_file: data/AMR/amr_2.0/amr2.0_dev_dep_Allen.json
#train_srl_file: data/AMR/amr_2.0/amr2.0_train_srl.json
#dev_srl_file: data/AMR/amr_2.0/amr2.0_dev_srl.json

#----------------AMR3.0
#test: data/AMR/amr_3.0/test.txt
#train: data/AMR/amr_3.0/train.txt
#dev: data/AMR/amr_3.0/dev.txt
#train_dep_file: data/AMR/amr_3.0/amr3.0_train_dep_Allen.json
#dev_dep_file: data/AMR/amr_3.0/amr3.0_dev_dep_Allen.json
#train_srl_file: data/AMR/amr_3.0/amr3.0_train_srl.json
#dev_srl_file: data/AMR/amr_3.0/amr3.0_dev_srl.json

# ----------------bolt
#dev: data/AMR/bolt/amr-release-2.0-amrs-dev-bolt.txt
#train: data/AMR/bolt/amr-release-2.0-amrs-training-bolt.txt
#train_dep_file: data/AMR/bolt/bolt_train_dep_Allen.json
#dev_dep_file: data/AMR/bolt/bolt_dev_dep_Allen.json
#train_srl_file: data/AMR/bolt/bolt_train_srl_Allen.json
#dev_srl_file: data/AMR/bolt/bolt_dev_srl_Allen.json

# ----------------bfa
#dev: data/AMR/dfa/amr-release-2.0-amrs-dev-dfa.txt
#train: data/AMR/dfa/amr-release-2.0-amrs-training-dfa.txt
#train_dep_file: data/AMR/dfa/dfa-train-dep-Allen.json
#dev_dep_file: data/AMR/dfa/dfa-dev-dep-Allen.json
#train_srl_file: data/AMR/dfa/dfa-train-srl.json
#dev_srl_file: data/AMR/dfa/dfa-dev-srl.json

# ---------------lorelei
#dev: data/AMR/lorelei/amr-release-3.0-amrs-dev-lorelei.txt
#train: data/AMR/lorelei/amr-release-3.0-amrs-training-lorelei.txt
#train_dep_file: data/AMR/lorelei/lorelei-train-dep-Allen.json
#dev_dep_file: data/AMR/lorelei/lorelei-dev-dep-Allen.json
#train_srl_file: data/AMR/lorelei/lorelei-train-srl.json
#dev_srl_file: data/AMR/lorelei/lorelei-dev-srl.json

